### DISCUSSION TITLE
The presentation file does not load. *self-hosted

### DISCUSSION THREAD

**Discussion by zuf2002** [ClaperCo/Claper#47] [Q&A]
Good afternoon! I installed Claper on my own server, but I can't upload the presentation file to the system. The page takes a long time to load, but nothing happens (at the top of the page, the loading bar does not reach the end of the page). Can you tell me what can be done to fix this error and start using the system?

I installed the system using docker-compose. The site was published via reverse-proxy.

![2023-09-05_11-37-32](https://github.com/ClaperCo/Claper/assets/60726396/150a3dff-11c0-419a-b12c-cb7f1ef94acb)

**Comment by alxlion** [comment]
Hey ! 

I'd like to have some information about your setup. What's your Nginx configuration for Claper? Does it look like in the documentation? (https://docs.claper.co/deployment.html#behind-nginx) 

Do you have the same `Websocket connection failed` errors when you navigate through the app and do any action?

Can you share the Docker logs about the app? 

Thanks for your report

**Reply by zuf2002** [reply]
My setup is "out of the box":

```
git clone https://github.com/ClaperCo/Claper.git
cd Clapper
docker-layout
```

I also added docker-compose.yml maximum file size (100 MB).
That is all... I did not install Nginx, because the system started working by ip address and 4000 port.

Errors appear immediately upon entering the start page.

It is necessary to make the configuration from the instructions in docker-compose.yml file after the main configuration?

**Reply by zuf2002** [reply]
the Docker log is like this:

```
10:49:31.833 [error] Could not check origin for Phoenix.Socket transport.

Origin of the request: http://10.100.10.71:4000

This happens when you are attempting a socket connection to
a different host than the one configured in your config/
files. For example, in development the host is configured
to "localhost" but you may be trying to access it from
"127.0.0.1". To fix this issue, you may either:

  1. update [url: [host: ...]] to your actual host in the
     config file for your current environment (recommended)

  2. pass the :check_origin option when configuring your
     endpoint or when configuring the transport in your
     UserSocket module, explicitly outlining which origins
     are allowed:

        check_origin: ["https://example.com",
                       "//another.com:888", "//other.com"]


10:49:34.881 [error] Could not check origin for Phoenix.Socket transport.

Origin of the request: https://speech.*****

This happens when you are attempting a socket connection to
a different host than the one configured in your config/
files. For example, in development the host is configured
to "localhost" but you may be trying to access it from
"127.0.0.1". To fix this issue, you may either:

  1. update [url: [host: ...]] to your actual host in the
     config file for your current environment (recommended)

  2. pass the :check_origin option when configuring your
     endpoint or when configuring the transport in your
     UserSocket module, explicitly outlining which origins
     are allowed:

        check_origin: ["https://example.com",
                       "//another.com:888", "//other.com"]
```

and many similar entries

**Reply by alxlion** [reply]
When you use the original `docker-compose.yml` file, you can access directly Claper at the address `http://localhost:4000`. Here you try to access with `10.100.10.71:400` so for security reasons it doesn't work.

Try to add this to your docker-compose file `ENDPOINT_HOST: 10.100.10.71`, so your file looks like:
```
version: "3.0"
services:
  db:
    image: postgres:9
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: claper
      POSTGRES_USER: claper
      POSTGRES_DB: claper
  app:
    image: ghcr.io/claperco/claper:latest
    ports: 
      - 4000:4000
    volumes:
      - uploads:/app/priv/static/uploads
    environment:
      DATABASE_URL: postgres://claper:claper@db:5432/claper
      SECRET_KEY_BASE: 0LZiQBLw4WvqPlz4cz8RsHJlxNiSqM9B48y4ChyJ5v1oA0L/TPIqRjQNdPZN3iEG
      MAIL_TRANSPORT: local
      ENDPOINT_PORT: 4000
      ENDPOINT_HOST: 10.100.10.71
    depends_on:
      - db
volumes:
  uploads:
```
