### ISSUE TITLE
Claper behind Traefik Reverse Proxy

### ISSUE THREAD

**Issue by holema** [ClaperCo/Claper#11]
Hello,
 thanks for the project.
I wanted to install it in my trafik cluster behind a trafik reverse proxy.
For this I build the following docker-compose.yml file.

```
# docker-compose.yml 
version: '3'

services:
  claper:
    #build: .
    image: ghcr.io/claperco/claper:main
    container_name: claper
    restart: always
    security_opt:
      - no-new-privileges:true
    environment:
      DATABASE_URL: postgresql://claper:claper@postgres:5432/claper
      SECRET_KEY_BASE: kjsdfhkhjfkjdshkfjhds
      #ENDPOINT_HOST: claper.mydomain.com
      #ENDPOINT_PORT: 4000
    networks:
      - default
      - intern
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.claper.tls=true"
      - "traefik.http.routers.claper.rule=Host(`claper.mydomain.com`)"
      - "traefik.http.routers.claper.entrypoints=web"
      - "traefik.http.services.claper.loadbalancer.server.port=4000"
      - "traefik.http.routers.claper.tls.certresolver=letsencrypt"
  postgres:
    #build: .
    image: postgres:9
    restart: always
    environment:
      POSTGRES_PASSWORD: claper
      POSTGRES_USER: claper
      POSTGRES_DB: claper
    security_opt:
      - no-new-privileges:true

    networks:
      - intern

networks:
  default:
    external:
      name: gateway
  intern:
    internal: true
```

Did anyone tried it already with a reverse-Proxy in front of the Claper service?

The claper container is starting and it says:
```
claper             | 09:05:43.314 [info] Running ClaperWeb.Endpoint with cowboy 2.9.0 at :::4000 (http)
claper             | 09:05:43.335 [info] Access ClaperWeb.Endpoint at http://localhost
```

**Comment by alxlion** [comment]
Hi,

You need to uncomment `ENDPOINT_HOST: claper.mydomain.com` and `ENDPOINT_PORT: 4000` in your file.

This is a docker-compose file with traefik that works well: 

```
version: "3.0"
services:
  db:
    image: postgres:9
    environment:
      POSTGRES_PASSWORD: claper
      POSTGRES_USER: claper
      POSTGRES_DB: claper
  app:
    build: .
    environment:
      DATABASE_URL: postgres://claper:claper@db:5432/claper
      SECRET_KEY_BASE: 0LZiQBLw4WvqPlz4cz8RsHJlxNiSqM9B48y4ChyJ5v1oA0L/TPIqRjQNdPZN3iEG
      MAIL_TRANSPORT: local
      ENDPOINT_HOST: claper.local
      ENDPOINT_PORT: 4000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.claper.rule=Host(`claper.local`)"
      - "traefik.http.routers.claper.entrypoints=web"
    depends_on:
      - db
      - traefik

  traefik:
    image: traefik
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "80:80"
      - "8080:8080"
```

Using this configuration allow your to access Claper on `http://clape.local`
