### ISSUE TITLE
Authelia OICD login fails due to missing state value

### ISSUE THREAD

**Issue by DaniW42** [ClaperCo/Claper#143]
I did set up OIDC with Authelia. I guess the Authelia client side is Ok as I use nearly the same config for all my OIDC Clients. When I click on Login I get the following message. (I am using Claper with Docker Compose and behind Nginx Proxy Manager.)

> The site is under maintenance, we'll be back very soon!

<img width="542" alt="Image" src="https://github.com/user-attachments/assets/051bc126-1a75-419c-96e4-7efdef30bc29" />

**The relevant claper-app logs show:**
```
05:17:58.038 request_id=GDa0yE1wZSBrScMAARTh [info] GET /users/log_in
05:17:58.039 request_id=GDa0yE1wZSBrScMAARTh [info] Sent 302 in 668µs
05:17:58.319 request_id=GDa0yF42Rxu3ddAAARTx [info] GET /users/oidc
05:17:58.671 request_id=GDa0yF42Rxu3ddAAARTx [info] Sent 500 in 352ms
05:17:58.672 [error] #PID<0.8639.0> running ClaperWeb.Endpoint (connection #PID<0.8638.0>, stream id 1) terminated
Server: claper.<mydomain>.dev:80 (http)
Request: GET /users/oidc
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, {:http_error, 400, %{"error" => "invalid_state", "error_description" => "The state is missing or does not have enough characters and is therefore considered too weak. Request parameter 'state' must be at least be 8 characters long to ensure sufficient entropy."}}}
        (claper 2.3.1) lib/claper_web/controllers/user_oidc_auth.ex:12: ClaperWeb.UserOidcAuth.new/2
        (claper 2.3.1) lib/claper_web/controllers/user_oidc_auth.ex:1: ClaperWeb.UserOidcAuth.action/2
        (claper 2.3.1) lib/claper_web/controllers/user_oidc_auth.ex:1: ClaperWeb.UserOidcAuth.phoenix_controller_pipeline/2
        (phoenix 1.7.11) lib/phoenix/router.ex:484: Phoenix.Router.__call__/5
        (claper 2.3.1) lib/claper_web/endpoint.ex:1: ClaperWeb.Endpoint.plug_builder_call/2
        (claper 2.3.1) lib/claper_web/endpoint.ex:1: ClaperWeb.Endpoint.call/2
        (plug_cowboy 2.7.2) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
        (cowboy 2.12.0) /app/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
```

**The relevant authelia logs show:**
```
time="2025-04-16T08:06:54+02:00" level=error msg="Pushed Authorization Request failed with error: The state is missing or does not have enough characters and is therefore considered too weak. Request parameter 'state' must be at least be 8 characters long to ensure sufficient entropy." method=POST path=/api/oidc/pushed-authorization-request remote_ip=172.18.0.1
```

So I guess the resulting error is:

> The state is missing or does not have enough characters and is therefore considered too weak. Request parameter 'state' must be at least be 8 characters long to ensure sufficient entropy.

_There is an issue at the Authelia issues (https://github.com/authelia/authelia/issues/9003) which mentions the same error message. I am not into OIDC enough to fully understand it but it looks like Claper is possibly missing UserInfo Endpoint support? The same problem occured on the Homarr Issues (https://github.com/homarr-labs/homarr/issues/2635) and the developer seemed to have fixed it pretty fast, so maybe this is not a huge change?_

Let me add that I already tried the workaround (https://www.authelia.com/integration/openid-connect/openid-connect-1.0-claims/#restore-functionality-prior-to-claims-parameter) which would probably be fine for me but it didn't changed a thing at all.

**Comment by alxlion** [comment]
Thanks for the report 🙏 

I'll check to run an Authelia instance to test Claper and fix the problem asap.

**Comment by DaniW42** [comment]
If I can help, let me know!

**Comment by james-d-elliott** [comment]
This may be caused due to Authelia implementing claims hydration in the conformant way where claims only exist in the appropriate place. Since Pangolin does not use the implicit flow solely returning an ID Token the ID Token, and Grafana is not requesting the claims be present in the ID Token, these claims shouldn't be present in the ID Token and should instead be retrieved using the Access Token from the UserInfo Endpoint.

Please feel free to take a look at a [Work In Progress Blog Article](https://deploy-preview-9349--authelia-staging.netlify.app/blog/technical-openid-connect-1.0-nuances/) (specifically claims availability) for a mid level explanation on all of these nuances with the spec which will assist with resolving this bug. We have a formal workaround for clients that do not properly support the spec documented [here](https://www.authelia.com/integration/openid-connect/openid-connect-1.0-claims/#restore-functionality-prior-to-claims-parameter) which has been confirmed to work in this instance.

**Comment by james-d-elliott** [comment]
I probably should have more carefully read this, the above post is not related to this unless it's an issue obtaining claims.

**Comment by DaniW42** [comment]
I have tried to do it with the docs mentioned in the post, but had no luck. I will do my best to create an article for the authelia docs if somebody could lead me to a working solution.

**Comment by james-d-elliott** [comment]
I believe the issue is the parameter entropy defaults. We require a state parameter with at least 8 characters. From the look of the error you may be able to set [minimum_parameter_entropy](https://www.authelia.com/configuration/identity-providers/openid-connect/provider/#minimum_parameter_entropy) to -1 to get this to work.

**Comment by DaniW42** [comment]
I'll give it a try and let you know. Are there any plans on implementing such a feature?

**Comment by james-d-elliott** [comment]
> [@DaniW42](https://github.com/DaniW42) [@james-d-elliott](https://github.com/james-d-elliott) Do you have an Authelia configuration example for Claper that I can test (especially the identity_providers > oidc settings) ?

I'll try to coordinate this over the weekend, been very busy sorry.

**Comment by alxlion** [comment]
> > [@DaniW42](https://github.com/DaniW42) [@james-d-elliott](https://github.com/james-d-elliott) Do you have an Authelia configuration example for Claper that I can test (especially the identity_providers > oidc settings) ?
> 
> I'll try to coordinate this over the weekend, been very busy sorry.

No problem thanks for your time

**Comment by james-d-elliott** [comment]
@alxlion can you contact me via one of the means in my profile? Discord or Matrix. I think it'd be simpler to just give you some credentials on my dev instance and set the client up for you.

**Comment by lucasew** [comment]
How big is the value being passed to the SECRET_KEY_BASE environment variable at runtime?

That should be a big random string.

My hypothesis is that it's not defined.

**Comment by alxlion** [comment]
> How big is the value being passed to the SECRET_KEY_BASE environment variable at runtime?
> 
> That should be a big random string.
> 
> My hypothesis is that it's not defined.

This uses the command `openssl rand -base64 48` which should produce a 64-character base64-encoded string derived from 48 securely generated random bytes (like `ngi9/vQto5GVMKqrU1kCBMWlQpdCNGn5AzOMi1XHs64YNSTPWGLoRiQJxYbfmllm`)

**Comment by alxlion** [comment]
> [@alxlion](https://github.com/alxlion) can you contact me via one of the means in my profile? Discord or Matrix. I think it'd be simpler to just give you some credentials on my dev instance and set the client up for you.

Stay in touch on Discord

**Comment by james-d-elliott** [comment]
@alxlion I have tested #154 and can test #152 as well if you prefer. There's one issue I noticed during testing which was that Claper expects scoped claims hydration in the ID Token which is out-of-spec (User Info Endpoint should be used for OIDC). There's an escape hatch in Authelia for this though.

**Comment by alxlion** [comment]
Authelia is still causing problems with Claper, it's the only OIDC provider to have failed to date. 

Claper sends a POST request to the URL `/api/oidc/pushed-authorization-request` with the following body : `client_id=XXX&request=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJodHRwczovL2F1dGguY2xhcGVyLmNvIiwiY2xpZW50X2lkIjoiVUpEcjJ4azVlRUZLNlNmQW4yVTZWRUhZTjY1cWNFUGhCdldvNGNxcnNidWJvQzZEb21xWWc2Q25BQjlUUkxEdUdFOHlDb0tyIiwiY29kZV9jaGFsbGVuZ2UiOiJFa1RfTnl4bHNlMFFGQUhUbGRoT0YzajlTNXN3VmlVUTVLT3hTN2hBUHpFIiwiY29kZV9jaGFsbGVuZ2VfbWV0aG9kIjoiUzI1NiIsImV4cCI6MTc2MjA4MjIyNiwiaWF0IjoxNzYyMDgyMTk2LCJpc3MiOiJVSkRyMnhrNWVFRks2U2ZBbjJVNlZFSFlONjVxY0VQaEJ2V280Y3Fyc2J1Ym9DNkRvbXFZZzZDbkFCOVRSTER1R0U4eUNvS3IiLCJqdGkiOiJRV3BsYS03dzVTcHhUVEF6YmU2SFJZN0w0bzFEcG4wSjFjclZWTU9wemVVIiwibmJmIjoxNzYyMDgyMTk2LCJyZWRpcmVjdF91cmkiOiJodHRwOi8vbG9jYWxob3N0OjQwMDAvdXNlcnMvb2lkYy9jYWxsYmFjayIsInJlc3BvbnNlX3R5cGUiOiJjb2RlIiwic2NvcGUiOiJvcGVuaWQgZW1haWwgcHJvZmlsZSJ9.jBvx_FNcVtmXmyHbsTXT1YezUCIyrcp4JzTPe90wHXs&response_type=code&scope=openid+email+profile` 
However, Authelia keeps responding with a **400 Bad Request** error: `{"error":"invalid_request_object","error_description":"The request parameter contains an invalid Request Object. OpenID Connect 1.0 request object could not be decoded or validated."}`

Using jwt.io, the JWT is found to be valid and correctly encoded with the client secret.

Authelia conf: 


```
clients:
      - client_id: 'UJDr2xk5eEFK6SfAn2U6VEHYN65qcEPhBvWo4cqrsbuboC6DomqYg6CnAB9TRLDuGE8yCoKr' 
        client_name: 'Claper'
        client_secret: '$pbkdf2-sha512$310000$y0iT5ITxTxLLBE7Q0EWj4A$fF62q4lJpYvWFw9p1o1XJfMApzCz24/D2m.KABgVgWSC.IKxKYo40/5brpj6hsqe1CeP3BYSvZ0RBt6vnwyfUg'  # The digest of 'fBQVHe_OvoChQhZcgTP015zHWs62doUaer5oATUmT5qGSYcqxxKj34p3vf7TAH0WbWRVpFP6'.
        public: false
        redirect_uris:
          - 'http://localhost:4000/users/oidc/callback'
        scopes:
          - 'openid'
          - 'email'
          - 'profile'
        grant_types:
          - 'authorization_code'
        response_types:
          - 'code'
        authorization_policy: 'two_factor'
        token_endpoint_auth_method: 'client_secret_basic'
        require_pkce: true
        pkce_challenge_method: 'S256'
```

**Comment by james-d-elliott** [comment]
The request object implementation we use is formally certified by the OpenID Foundation. Also it's not possible with that configuration that the JWT has been correctly minted. It's using the HS256 alg but there is no way to validate the signature in your config.

Authelia has **_correctly rejected_** that JWT as it's **_not possible_** to validate it.

**Comment by james-d-elliott** [comment]
To demonstrate the impossibility [jwt.io](https://www.jwt.io/) has exactly the same issue validating it when provided the same information as you've provided Authelia:

<img width="1347" height="1216" alt="Image" src="https://github.com/user-attachments/assets/a33de22a-9bfc-44af-9f1a-56e96b075984" />

---

You must use a plaintext secret and configure the correct signing alg to use secret-based JWT's. 

Example:

```yaml
identity_providers:
  oidc:
    clients:
      - client_id: 'UJDr2xk5eEFK6SfAn2U6VEHYN65qcEPhBvWo4cqrsbuboC6DomqYg6CnAB9TRLDuGE8yCoKr' 
        client_name: 'Claper'
        client_secret: '$plaintext$fBQVHe_OvoChQhZcgTP015zHWs62doUaer5oATUmT5qGSYcqxxKj34p3vf7TAH0WbWRVpFP6'
        public: false
        redirect_uris:
          - 'http://localhost:4000/users/oidc/callback'
        scopes:
          - 'openid'
          - 'email'
          - 'profile'
        grant_types:
          - 'authorization_code'
        response_types:
          - 'code'
        authorization_policy: 'two_factor'
        request_object_signing_alg: 'HS256' 
        token_endpoint_auth_method: 'client_secret_basic'
        require_pkce: true
        pkce_challenge_method: 'S256'
```

---

If there are other providers that accept this JWT without a plaintext secret it's an abundantly clear critical vulnerability and you should report this through the correct avenues without discussing it publicly. It indicates they are not performing any signature validation on request objects which is strictly required.
