### ISSUE TITLE
Claper behind Traefik Revers Proxy with "environment: - BASE_PATH=/claper/" with e.g. https://sub.domain.com/claper as home URL

### ISSUE THREAD

**Issue by E-J-D** [ClaperCo/Claper#145]
I try to run Claper with Portainer stack / (Docker compose) behind a Traefik reverse proxy. Because of tricky domain management I need to run Claper with a home dir instead of subdomain. This is the way I manage to use other docker container as well. From other docker container I already learned that we need the environment variable "BASE_PATH" for this usecase. It seems to me that the environment variable "BASE_PATH" is not yet implemented in Claper. 

The container start but the webside prompts "Oops, page doesn't exist. Return to home."

My docker compose looks like this...

```
services:
  db:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - "claper-db:/var/lib/postgresql/data"
    healthcheck:
      test:
        - CMD
        - pg_isready
        - "-q"
        - "-d"
        - "claper"
        - "-U"
        - "claper"
      retries: 3
      timeout: 5s
    environment:
      - POSTGRES_PASSWORD=claper
      - POSTGRES_USER=claper
      - POSTGRES_DB=claper
      - BASE_PATH=/claper/
    networks:
      - claper-net

  app:
    image: ghcr.io/claperco/claper:latest
    ports:
      - 4000:4000
    volumes:
      - "claper-uploads:/app/uploads"
    healthcheck:
      test: curl --fail http://localhost:4000 || exit 1
      retries: 3
      start_period: 20s
      timeout: 5s
    env_file: stack.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - claper-net
      - proxy
    labels:
      - "traefik.enable=true" # <== Enable traefik 
      - "traefik.http.routers.claper.entrypoints=web,websecure"
      - "traefik.http.routers.claper.rule=Host(`sub.domain.com`) && PathPrefix(`/claper`)"
      - "traefik.http.routers.claper.service=claper-service"
      - "traefik.http.routers.claper.tls.certresolver=letsencrypt"
      - "traefik.http.routers.claper.tls=true"
      - "traefik.http.services.claper-service.loadbalancer.server.port=4000"

  traefik:
    image: traefik:v3.1
    container_name: traefik_v3
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Berlin
    networks:
      - proxy
    ports:
      - 80:80 # HTTP entryPoints
      - 443:443 # HTTPS entryPoints
      - 8080:8080 # Dashbaord WebGui 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /docker-data/traefik_v3/traefik.yml:/traefik.yml:ro
      - /docker-data/traefik_v3_certs:/certs

volumes:
  claper-db:
    driver: local
  claper-uploads:
    driver: local

networks:
  proxy:
    external: true
  claper-net:
    driver: bridge
```

As BASE_URL I set "https://sub.domain.com/claper".

Thanks for your help and thanks for this great project!
