### ISSUE TITLE
[Question] Account creation possible despite .env setting

### ISSUE THREAD

**Issue by gkruger1** [ClaperCo/Claper#31]
Awesome app!

I've got ENABLE_ACCOUNT_CREATION:false in .env but, for some reason, the Create Account link still shows and it's still possible to create an account. 

I would appreciate any suggestions about what I'm doing wrong.

Ubuntu 22.04.2 LTS
Docker client 23.0.1
Docker server 20.10.23

**Comment by alxlion** [comment]
Hi,

Can you share your Docker Compose file ?

**Comment by alxlion** [comment]
In your environment you don't have any ENABLE_ACCOUNT_CREATION variable.
You only have:
```
environment:
      DATABASE_URL: postgres://claper:claper@db:5432/claper
      SECRET_KEY_BASE: 0LZiQBLw4WvqPlz4cz8RsHJlxNiSqM9B48y4ChyJ5v1oA0L/TPIqRjQNdPZN3iEG
      MAIL_TRANSPORT: local
      ENDPOINT_HOST: 194-146-24-75.cloud-xip.com
      ENDPOINT_PORT: 4000
```
