### ISSUE TITLE
Is it possible to upload a much much larger presentation size?

### ISSUE THREAD

**Issue by Pedroman1** [ClaperCo/Claper#44]
New to docker just getting setup locally but it seems like I still have a 15mb limit? I have a presentation approx 500mb was hoping to try this out with. Is it possible to accomplish this?

**Comment by alxlion** [comment]
Can you please show me your `docker-compose.yml` ? Or the configuration you use ?

**Comment by Pedroman1** [comment]
Thanks for the reply and  I apologize ahead of time I just use github for stable diffusion and some large language model stuff which typically has instructions for people new to github etc. I have never used docker before and really have no idea what I am doing to install this but it sounds awesome and I have a presentation on wednesday I'd love to try it for. If I ever do figure out how to use it I'll try to upload a video or soemthing how to install it to youtube and use it. 


The way I have done it is gone to my intended install directory (using windows btw) then opened command prompt

> **git clone https://github.com/ClaperCo/Claper.git**

##I then changed the sample.env file to simply .env and changed within it the maximum upload file size from 15 mb to 1000 mb) ##

**

> cd Claper
> docker-compose up

**
But then it still won't let me upload anything larger....

**Comment by alxlion** [comment]
Docker compose doesn't use your `.env` file, you have to write your configuration inside the `docker-compose.yml` in the `environment` of the app :

```
version: "3.0"
services:
  db:
    image: postgres:9
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: claper
      POSTGRES_USER: claper
      POSTGRES_DB: claper
  app:
    image: ghcr.io/claperco/claper:latest
    ports: 
      - 4000:4000
    volumes:
      - uploads:/app/priv/static/uploads
    environment:
      DATABASE_URL: postgres://claper:claper@db:5432/claper
      SECRET_KEY_BASE: 0LZiQBLw4WvqPlz4cz8RsHJlxNiSqM9B48y4ChyJ5v1oA0L/TPIqRjQNdPZN3iEG
      MAIL_TRANSPORT: local
      ENDPOINT_PORT: 4000
      MAX_FILE_SIZE_MB: 1000
    depends_on:
      - db
volumes:
  uploads:
```
